name: Gardensteader
favicon: null
layout_spectrum: 0.9759594015777111
typography_spectrum: 0.6006082978565246
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.05778424860909581
  lightness: 0.7945859038736671
  saturation: 0.21057985164225101
  rhythmicContrast: 0.9907222799956799
purpose: []
