name: Gardensteader
favicon: null
layout_spectrum: 0.9759594015777111
typography_spectrum: 0.6006082978565246
title: Gardensteader - Micro Farming Meets Urban Homesteading
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#38333a'
    - '#fffffd'
    - '#d6dbb2'
    - '#a0a774'
    - '#557d03'
  brandStrength: 0.0625
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
